"use client";

import { useActionState, useMemo, useState } from "react";
import Link from "next/link";
import { createEnrollmentAccountAction, submitEnrollmentAction } from "./actions";
import { HumanVerification } from "@/components/security/HumanVerification";
import { TataLoading } from "@/components/tata/TataLoading";

const input = "min-h-12 w-full rounded-2xl border border-tata-border bg-white px-4 py-3 text-sm outline-none focus:border-tata-green focus:ring-2 focus:ring-tata-green/20";
const label = "flex flex-col gap-1.5 text-sm font-semibold text-tata-ink";
type Person = { name: string; cpf: string; phone: string; relationship: string; notes: string };

export function AccountForm() {
  const [state, action, pending] = useActionState(createEnrollmentAccountAction, undefined);
  if (state?.success) return <div className="rounded-3xl bg-white p-6 shadow-tata-card text-center"><div className="text-4xl">💛</div><h2 className="font-[family-name:var(--font-baloo)] text-xl font-bold text-tata-green-dark">Conta criada!</h2><p className="mt-2 text-sm text-tata-ink-soft">Entre com seu e-mail e senha para continuar a matrícula.</p><Link href="/login?callbackUrl=/matricula" className="mt-5 inline-flex min-h-12 items-center rounded-2xl bg-tata-coral px-6 font-bold text-white">ENTRAR E CONTINUAR</Link></div>;
  return <form action={action} aria-busy={pending} className="rounded-3xl bg-white p-5 sm:p-7 shadow-tata-card flex flex-col gap-4"><TataLoading active={pending} context="SUBMIT" message="Criando conta..." />
    <div><p className="text-xs font-bold uppercase tracking-wider text-tata-green-dark">Etapa 1 de 7</p><h1 className="font-[family-name:var(--font-baloo)] text-2xl font-bold text-tata-ink">Crie sua conta de responsável</h1><p className="text-sm text-tata-ink-soft">Ela será usada para acompanhar a solicitação com segurança.</p></div>
    <label className={label}>Nome completo<input name="name" autoComplete="name" required className={input}/></label>
    <div className="grid sm:grid-cols-2 gap-4"><label className={label}>CPF<input name="cpf" inputMode="numeric" required className={input}/></label><label className={label}>Data de nascimento<input name="birthDate" type="date" required className={input}/></label></div>
    <div className="grid sm:grid-cols-2 gap-4"><label className={label}>Telefone<input name="phone" type="tel" inputMode="tel" required className={input}/></label><label className={label}>WhatsApp<input name="whatsapp" type="tel" inputMode="tel" className={input}/></label></div>
    <label className={label}>E-mail<input name="email" type="email" autoComplete="email" required className={input}/></label>
    <div className="grid sm:grid-cols-2 gap-4"><label className={label}>Senha<input name="password" type="password" minLength={8} autoComplete="new-password" required className={input}/></label><label className={label}>Confirmar senha<input name="confirmPassword" type="password" minLength={8} autoComplete="new-password" required className={input}/></label></div>
    <label className="flex gap-3 text-sm text-tata-ink-soft"><input name="privacyAccepted" type="checkbox" required className="mt-3 size-5 accent-tata-green"/><span>Li e aceito a <Link href="/politica-de-privacidade" className="inline-flex min-h-11 items-center font-bold underline">Política de Privacidade</Link>.</span></label>
    {state?.error && <p role="alert" className="text-sm font-semibold text-tata-coral-dark">{state.error}</p>}
    <HumanVerification pending={pending} />
    <button disabled={pending} className="min-h-12 rounded-2xl bg-tata-coral px-6 font-bold text-white disabled:opacity-60">{pending ? "CRIANDO..." : "CRIAR CONTA"}</button>
    <p className="text-center text-sm text-tata-ink-soft">Já tem conta? <Link href="/login?callbackUrl=/matricula" className="inline-flex min-h-11 items-center font-bold text-tata-green-dark">Entrar</Link></p>
  </form>;
}

export function EnrollmentWizard({ guardianName, guardianCpf, guardianPhone, guardianEmail }: { guardianName: string; guardianCpf: string; guardianPhone: string; guardianEmail: string }) {
  const [step, setStep] = useState(2); const [state, action, pending] = useActionState(submitEnrollmentAction, undefined);
  const [people, setPeople] = useState<Person[]>([]); const [draft, setDraft] = useState<Person>({ name: "", cpf: "", phone: "", relationship: "OTHER", notes: "" });
  const title = useMemo(() => ["", "", "Responsável", "Criança", "Cuidados", "Pessoas autorizadas", "Revisão"][step], [step]);
  if (state?.success) return <div className="rounded-3xl bg-white p-7 shadow-tata-card text-center"><div className="text-5xl">💛</div><h1 className="font-[family-name:var(--font-baloo)] text-2xl font-bold text-tata-green-dark">Matrícula enviada!</h1><p className="mt-2 text-tata-ink-soft">Recebemos os dados. Nossa equipe fará a análise e você verá a decisão aqui.</p><div className="mt-5 rounded-2xl bg-tata-yellow/15 px-4 py-3 font-bold text-tata-yellow-dark">🟡 AGUARDANDO APROVAÇÃO</div></div>;
  return <form action={action} aria-busy={pending} className="rounded-3xl bg-white p-5 sm:p-7 shadow-tata-card flex flex-col gap-5"><TataLoading active={pending} context="ENROLLMENT" />
    <input type="hidden" name="authorizedPeople" value={JSON.stringify(people)}/>
    <div><div className="flex justify-between text-xs font-bold text-tata-green-dark"><span>Etapa {step} de 7</span><span>{title}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-tata-green/10"><div className="h-full rounded-full bg-tata-green transition-all" style={{width:`${step / 7 * 100}%`}}/></div></div>
    <section className={step === 2 ? "flex flex-col gap-3" : "hidden"}><h2 className="font-[family-name:var(--font-baloo)] text-xl font-bold">Olá, {guardianName.split(" ")[0]}!</h2><p className="text-sm text-tata-ink-soft">Vamos iniciar a matrícula da sua criança? Seus dados já estão seguros conosco.</p><div className="rounded-2xl bg-tata-surface-alt p-4 text-sm"><p><b>Nome:</b> {guardianName}</p><p><b>CPF:</b> {guardianCpf}</p><p><b>Telefone:</b> {guardianPhone}</p><p><b>E-mail:</b> {guardianEmail}</p></div><label className={label}>Relação com a criança<select name="relationship" defaultValue="LEGAL_GUARDIAN" className={input}><option value="MOTHER">Mãe</option><option value="FATHER">Pai</option><option value="LEGAL_GUARDIAN">Responsável legal</option><option value="OTHER">Outro</option></select></label></section>
    <section className={step === 3 ? "grid sm:grid-cols-2 gap-4" : "hidden"}><label className={`${label} sm:col-span-2`}>Nome completo<input name="childFullName" required className={input}/></label><label className={label}>Nome social / como prefere ser chamada<input name="childPreferredName" className={input}/></label><label className={label}>Data de nascimento<input name="childBirthDate" type="date" required className={input}/></label><label className={label}>Sexo<select name="childSex" required defaultValue="" className={input}><option value="" disabled>Selecione</option><option value="FEMALE">Feminino</option><option value="MALE">Masculino</option></select></label><label className={label}>CPF, se houver<input name="childCpf" inputMode="numeric" className={input}/></label><label className={`${label} sm:col-span-2`}>Certidão de nascimento, se necessário<input name="birthCertificate" className={input}/></label></section>
    <section className={step === 4 ? "grid sm:grid-cols-2 gap-4" : "hidden"}>{[["allergies","Alergias"],["dietaryRestrictions","Restrições alimentares"],["medications","Medicamentos"],["relevantConditions","Condições relevantes"],["specificNeeds","Necessidades específicas"],["importantCareInfo","Informações importantes para o cuidado"],["generalNotes","Observações gerais"]].map(([name,text])=><label key={name} className={`${label} ${name === "generalNotes" ? "sm:col-span-2" : ""}`}>{text}<textarea name={name} rows={3} className={input}/></label>)}</section>
    <section className={step === 5 ? "flex flex-col gap-4" : "hidden"}><p className="text-sm text-tata-ink-soft">Cadastre quem pode buscar a criança. Isso não concede acesso ao Portal dos Pais.</p>{people.map((p,i)=><div key={i} className="rounded-2xl bg-tata-surface-alt p-3 text-sm flex justify-between"><span><b>{p.name}</b><br/>{p.phone}</span><button type="button" onClick={()=>setPeople(people.filter((_,x)=>x!==i))} className="text-tata-coral-dark font-bold">Remover</button></div>)}<div className="grid sm:grid-cols-2 gap-3"><input aria-label="Nome da pessoa autorizada" placeholder="Nome" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className={input}/><input aria-label="Telefone da pessoa autorizada" placeholder="Telefone" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})} className={input}/><input aria-label="CPF da pessoa autorizada" placeholder="CPF/documento" value={draft.cpf} onChange={e=>setDraft({...draft,cpf:e.target.value})} className={input}/><select aria-label="Relação da pessoa autorizada" value={draft.relationship} onChange={e=>setDraft({...draft,relationship:e.target.value})} className={input}><option value="GRANDMOTHER">Avó</option><option value="GRANDFATHER">Avô</option><option value="AUNT">Tia</option><option value="UNCLE">Tio</option><option value="OTHER">Outra relação</option></select></div><button type="button" onClick={()=>{if(draft.name&&draft.phone){setPeople([...people,draft]);setDraft({name:"",cpf:"",phone:"",relationship:"OTHER",notes:""})}}} className="min-h-11 rounded-2xl border border-tata-green font-bold text-tata-green-dark">+ ADICIONAR PESSOA</button></section>
    <section className={step === 6 ? "flex flex-col gap-4" : "hidden"}><h2 className="font-[family-name:var(--font-baloo)] text-xl font-bold">Revise sua matrícula</h2><p className="text-sm text-tata-ink-soft">Confira os campos das etapas anteriores. Você poderá acompanhar o status após o envio.</p><div className="rounded-2xl bg-tata-surface-alt p-4 text-sm"><b>Responsável</b><p>{guardianName} · {guardianEmail}</p><b className="mt-3 block">Pessoas autorizadas</b><p>{people.length ? people.map(p=>p.name).join(", ") : "Nenhuma cadastrada"}</p></div><fieldset className="rounded-2xl border border-tata-border p-4 flex flex-col gap-2 text-sm"><legend className="px-2 font-bold">Autorizações de imagem (separadas)</legend>{[["imageAuthInternal","Registro interno"],["imageAuthGuardianShare","Compartilhamento com responsável"],["imageAuthInstitutional","Comunicação institucional"],["imageAuthSocialMedia","Redes sociais"],["imageAuthAdvertising","Publicidade"]].map(([name,text])=><label key={name} className="flex gap-2"><input name={name} type="checkbox" className="size-5 accent-tata-green"/>{text}</label>)}</fieldset></section>
    {state?.error && <p role="alert" className="text-sm font-bold text-tata-coral-dark">{state.error}</p>}
    <div className="flex gap-3">{step>2&&<button type="button" onClick={()=>setStep(step-1)} className="min-h-12 flex-1 rounded-2xl border border-tata-border font-bold">VOLTAR</button>}{step<6?<button type="button" onClick={()=>setStep(step+1)} className="min-h-12 flex-[2] rounded-2xl bg-tata-coral font-bold text-white">CONTINUAR</button>:<button disabled={pending} className="min-h-12 flex-[2] rounded-2xl bg-tata-green font-bold text-white disabled:opacity-60">{pending?"ENVIANDO...":"ENVIAR MATRÍCULA"}</button>}</div>
  </form>;
}
