import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { EmptyState } from "@/components/tata/EmptyState";

export default async function EnrollmentsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const { status } = await searchParams; const allowed = ["SUBMITTED","UNDER_REVIEW","APPROVED","REJECTED"];
  const [requests, grouped] = await Promise.all([prisma.enrollmentRequest.findMany({ where: allowed.includes(status || "") ? { status: status as never } : { status: { in: ["SUBMITTED","UNDER_REVIEW"] } }, orderBy: { submittedAt: "desc" }, include: { guardian: true } }), prisma.enrollmentRequest.groupBy({ by: ["status"], _count: true })]);
  const count = Object.fromEntries(grouped.map(x=>[x.status,x._count]));
  return <div className="p-4 sm:p-8 flex flex-col gap-6"><div><h1 className="font-[family-name:var(--font-baloo)] text-2xl font-bold text-tata-ink">🎒 Matrículas</h1><p className="text-sm text-tata-ink-soft">Analise solicitações sem recadastrar a criança.</p></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["SUBMITTED","Novas"],["UNDER_REVIEW","Em análise"],["APPROVED","Aprovadas"],["REJECTED","Rejeitadas"]].map(([s,l])=><Link key={s} href={`/admin/matriculas?status=${s}`} className="rounded-2xl bg-white p-4 shadow-sm"><b className="text-2xl text-tata-green-dark">{count[s]||0}</b><p className="text-xs text-tata-ink-muted uppercase">{l}</p></Link>)}</div>{!requests.length?<EmptyState message="Nenhuma matrícula nesta categoria." withMascot/>:<div className="grid gap-3">{requests.map(r=><article key={r.id} className="rounded-2xl bg-white p-4 shadow-sm flex flex-col sm:flex-row sm:items-center gap-3"><div className="flex-1"><h2 className="font-bold text-tata-ink">{r.childPreferredName || r.childFullName}</h2><p className="text-sm text-tata-ink-soft">Responsável: {r.guardian.name}</p><p className="text-xs text-tata-ink-muted">Solicitada em {r.submittedAt?.toLocaleString("pt-BR")}</p></div><span className="rounded-full bg-tata-yellow/15 px-3 py-1 text-xs font-bold text-tata-yellow-dark">{r.status}</span><Link href={`/admin/matriculas/${r.id}`} className="min-h-11 inline-flex items-center justify-center rounded-xl bg-tata-coral px-5 text-sm font-bold text-white">ANALISAR</Link></article>)}</div>}</div>;
}
